### PR TITLE
StreamProcessor for service to service messaging

### PR DESCRIPTION
**Pull request by artem-v**
Stream processor abstraction: 
``` java
**StreamProcessor**
  + onNext(StreamMessage): void
  + onError(Throwable): void
  + onCompleted(): void 
  + listen() : Observable<StreamMessage>
  + close() : void
```

Stream processor  factory object: 
```java
**StreamProcessors**
  + clientBootstrap(Bootstrap)
  + serverBootstrap(ServerBootStrap)
  + newClient(Address) : StreamProcessor

  + listen(String qualifier, Consumer<StreamProcessor> consumer) : void
```

Client usage: 
```java
    StreamProcessors streamProcessors = StreamProcessors.newStreamProcessors();

    StreamProcessor streamProcessor = streamProcessors.client(Address.from("192.168.1.3:5801"));

    streamProcessor.listen().subscribe(System.out::println, Throwable::printStackTrace);
    IntStream.rangeClosed(1, 1).forEach(i -> {
      streamProcessor.onNext(StreamMessage.withQualifier("q/hello").build());
    });
    streamProcessor.onCompleted();
```

Server usage:
```java
      StreamProcessors streamProcessors = StreamProcessors.newStreamProcessors();

      streamProcessors.server(streamProcessor -> streamProcessor.listen()
          .filter(message -> message.getQualifier().equalsIgnoreCase("q/hello"))
          .subscribe(message -> {
            streamProcessor.onNext(message);
            streamProcessor.onCompleted();
          }));

```

### CODE REVIEW

**Comment by ronenhamias** [comment]
I Suggest the following convention:

Rename exchange stream to RemoteStream and make kind of a factory

``` java
RemoteStream 
  + newRemoteStream(Address address, ServiceMessage messsage) : RemoteSubscription

RemoteSubscription  
  + subscribe() : Observable<ServiceMessage>
  + unsubscribe() ;
```

**Comment by artem-v** [comment]
Changed `ExchangeStream` to `SubscriberStream`. Added some sane code at last two commits.

**Comment by ronenhamias** [comment]
rename this module from:
scalecube-ipc to scalecube-streams

**Comment by ronenhamias** [comment]
streams/src/main/java/io/scalecube/streams/codec/ByteBufCodec.java
The method decode() has an NPath complexity of 271

**Pull request merged**
