### PR TITLE
Optional host address

### PR DESCRIPTION
**Pull request by mbarker**
Related to #197

### CODE REVIEW

**Comment by antonkharenko** [comment]
@mbarker Generally, I would like to elaborate a little more on your use case at https://github.com/scalecube/scalecube/issues/197 before merging this pull request. But anyway I think it would be reasonable to change it the following way:

* In TransportConfig what is currently called listenAddress/Port rename to bindAddress/Port
* In TransportConfig what you have introduced as hostAddress rename it to actually listenAddress and add listenPort since in general case it also may be different (e.g. you can map it on different port using docker -p option)
* The method Transport.address() should actually return listenAddress:Port (if not set then bindAddress:Port) so in such case you don't need to make any changes in MembershipProtocol.

**Comment by mbarker** [comment]
@antonkharenko Yep that seems pretty reasonable. I was hesitant to replace `Transport.address()` since that was used in lots of other places, and I was trying to limit the scope of the change to only publishing a different address/port. I think it totally makes sense to have a `bindAddress`/`bindPort` and `listenAddress`/`listenPort`. That certainly would work for our use case.

I discussed some other options with @ronenhamias on how I could use scalecube under docker. His suggestions all boiled down to all of the containers need to be on the same network (can be achieved with docker swarm/kubernetes/custom network shared across docker hosts). The reason I made the PR was I wanted to avoid changing the way we planning on deploying our containers. Also I wanted a better explanation of what I was thinking.

I can definitely provide more details about our use case if you'd like. Let me know what you want to know.

**Comment by mbarker** [comment]
I should also mention part of our use case is having docker containers and non docker containers (standalone java processes) form a `Cluster`.

**Comment by ronenhamias** [comment]
i guess my suggestion to use swarm or such is just one possible option that fits specific usecase and its not directly related to the specific change suggested as in this pull request. 
as i understand the possibility to select the host address to listen on is legit requirement regardless.

i was just wondering if listenAddress is not doing the same? maybe the name is not that intuitive and as anton suggested should be named bindAddress

**Comment by ronenhamias** [comment]
@antonkharenko @mbarker i am trying to understand the change and few questions came to my mind:

its not clear whats the difference between  Address and HostAddress:
Address - Returns local Address on which current instance of transport listens for incoming messages.
HostAddress - Returns host Address on which the current instance is accessible for incoming messages

also @antonkharenko :
what is the difference between bindAddress and listenAddress?

**Comment by mbarker** [comment]
Closing in favor of #203

**Pull request closed without merging**
